name: Auto Commit

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Make Changes
        run: |
          echo "Auto Commit: $(date)" >> log.txt

      - name: Commit and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git pull origin main --rebase  # Prevent conflicts
          git add .
          git commit -m "Auto commit - $(date)" || echo "No changes to commit"
          git push https://$GH_PAT@github.com/Minawahba98/autto.git main
