name: Auto Commit

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 1 minute for testing (change to "0 0 * * *" for daily runs)
  workflow_dispatch:  # Allows manual execution

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Prevents conflicts with GitHub token

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Pull Latest Changes
        run: |
          git pull origin main --rebase || echo "No changes to pull"

      - name: Update Log File
        run: echo "$(date)" >> log.txt  # Appends the current date to log.txt

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Auto commit: $(date)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
