name: Auto Commit
on:
  schedule:
- cron: '*/1 * * * *'  # Runs every minute
  workflow_dispatch:  # Allows manual execution

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Log File
        run: echo "$(date)" >> log.txt  # Appends the current date to log.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "minaadelbis2019@gmail.com"
